.TH SECRET 1
.SH NAME
"./secret" \- send file through secret channel to server and save it
.SH SYNOPSIS
.B "./secret" [-r FILE] [-s IP|HOSTNAME] [-l]
.SH DESCRIPTION
.B secret
encrypts data from file and sends them to server where server will save file.
.SH OPTIONS
.TP
.BR "-r file"
File to encrypt and send.
.TP
.BR "-s IP|HOSTNAME"
Hostname or IP where server is running.
.TP
.BR "-l"
Turn on server mode.
.SH MINIMAL LIBRARY VERSIONS
.TP
unistd.h – version 2.1
.TP
string.h – version 2.1
.TP
fstream – version 3.1
.TP
openssl/aes.h 
.TP
netdb.h – version 2.1
.TP
netinet/ip_icmp.h – version 2.1
.TP
vector – version 3.1
.TP
pcap.h 
.TP
netinet/ether.h – version 2.1
.TP
sys/poll.h – version 2.1
